spring:
  datasource:
    url:  jdbc:postgresql://sales-aurora.cluster-ce2znhoswsip.ap-northeast-1.rds.amazonaws.com:5432/jimba
    username: salesadmin
    password: adminsales
    driverClassName: org.postgresql.Driver
    
server: 
  port: 8090
